# Generated by Django 4.2.7 on 2023-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Formato: dd/mm/yyyy', null=True),
        ),
    ]
